#!/usr/bin/env node

import {getReleases} from '../lib/dl.google.com.js'

const releases = await getReleases(
  'https://developer.android.com/topic/generic-system-image/releases',
  /https:\/\/dl\.google\.com\/developers\/android\/[^\/]+?\/images\/gsi\/aosp_[^-]+?-exp-[^-]+?-[^-]+?-[^-]+?\.zip/,
  /^(?<target>aosp_.*?)-exp-(?<buildId>.*?)-.*?\.zip$/
)

console.log(JSON.stringify(releases, null, process.stdout.isTTY ? 2 : 0))
