name: release

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  aarch64:
    uses: ./.github/workflows/build.yml
    with:
      target: aosp_arm64
      image: https://dl.google.com/developers/android/vic/images/gsi/aosp_arm64-exp-AP3A.241005.015-12366759-3c0ee79d.zip
    secrets: inherit

  x86_64:
    uses: ./.github/workflows/build.yml
    with:
      target: aosp_x86_64
      image: https://dl.google.com/developers/android/vic/images/gsi/aosp_x86_64-exp-AP3A.241005.015-12366759-96716f9b.zip
    secrets: inherit

  build:
    needs: [aarch64, x86_64]

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4

      - name: Prepare
        run: |
          mkdir build
          mv build-aosp_arm64/aosp_arm64.tar.gz build/aarch64.tar.gz
          mv build-aosp_x86_64/aosp_x86_64.tar.gz build/x86_64.tar.gz

      - name: Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
