name: schedule

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  metadata:
    runs-on: ubuntu-latest

    outputs:
      releases: ${{ steps.releases.outputs.releases }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Get Generic System Image releases
        id: releases
        run: |
          if ${{ github.ref_type == 'tag' && 'true' || 'false' }}; then
            echo "releases=$(node index.mjs ${{ github.ref_name }})" | tee -a "$GITHUB_OUTPUT"
          else
            echo "releases=$(node index.mjs)" | tee -a "$GITHUB_OUTPUT"
          fi

  release:
    needs: [metadata]
    permissions:
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ fromJSON(needs.metadata.outputs.releases)[0].build }}
      artifacts: ${{ toJSON(fromJSON(needs.metadata.outputs.releases)[0].artifacts) }}
    secrets: inherit

  main:
    needs: [metadata]
    if: github.ref_type == 'branch'
    permissions:
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      artifacts: |
        [
          { "target": "aosp_arm64" },
          { "target": "aosp_x86_64" },
          { "target": "aosp_cf_riscv64_phone" }
        ]
    secrets: inherit
